-- 1. Inserindo as Categorias
INSERT INTO categorias (slug, nome, icone) VALUES 
('armario', 'Armários', 'armario'),
('banheiro', 'Banheiro', 'banho'),
('cozinha', 'Cozinha', 'cozinha'),
('escritorio', 'Escritório', 'escritorio'),
('guarda-roupa', 'Guarda Roupa', 'guarda-roupa'),
('hall', 'Hall', 'hall'),
('painel-sala', 'Painel', 'painel'),
('planejados-comercio', 'Comercial', 'comercio');

-- 2. Inserindo os Produtos
INSERT INTO produtos (id, nome, categoria, categoriaSlug, imagemPrincipal, imagens, descricao, destaque, relevancia) VALUES 
(1, 'Armário para Sala', 'Armários', 'armario', '/images/produtos/armario/armario-sala.jpeg', '["/images/produtos/armario/armario-sala.jpeg"]', 'Armário planejado sob medida, ideal para a organização de itens e otimização de espaço na sala de estar, garantindo um visual minimalista e elegante.', 0, 4),
(2, 'Armário Banheiro Planejado', 'Banheiros', 'banheiro', '/images/produtos/banheiro/banheiro-1.jpg', '["/images/produtos/banheiro/banheiro-1.jpg","/images/produtos/banheiro/banheiro-2.jpg","/images/produtos/banheiro/banheiro-3.jpg"]', 'Conjunto completo de marcenaria para banheiro planejado, composto por armários de excelente divisória e resistente à umidade típica do ambiente.', 0, 3),
(3, 'Área Gourmet Planejada', 'Cozinhas', 'cozinha', '/images/produtos/cozinha/area-gourmet.jpg', '["/images/produtos/cozinha/area-gourmet.jpg"]', 'Projeto focado em áreas gourmet, perfeitamente alinhado com churrasqueiras e áreas de lazer, proporcionando funcionalidade e beleza nas suas recepções.', 0, 4),
(4, 'Cozinha Planejada Completa', 'Cozinhas', 'cozinha', '/images/produtos/cozinha/armario&movel-cozinha-.jpg', '["/images/produtos/cozinha/armario&movel-cozinha-.jpg"]', 'Conjunto de móveis para bancada e pia da cozinha. Acabamento moderno que facilita a limpeza no dia-a-dia.', 1, 3),
(5, 'Guarda Roupa Planejado Completo', 'Guarda Roupas', 'guarda-roupa', '/images/produtos/guarda-roupa/guarda-roupa-1.jpg', '["/images/produtos/guarda-roupa/guarda-roupa-1.jpg","/images/produtos/guarda-roupa/guarda-roupa-2.jpg","/images/produtos/guarda-roupa/guarda-roupa-3.jpg","/images/produtos/guarda-roupa/guarda-roupa-4.jpg"]', 'Guarda-roupa planejado completo com divisão inteligente, cabideiros reforçados, gavetas espaçosas e acabamento em MDF de altíssima qualidade.', 0, 5),
(6, 'Cozinha Planejada Moderna', 'Cozinhas', 'cozinha', '/images/produtos/cozinha/armario-cozinha-1.jpg', '["/images/produtos/cozinha/armario-cozinha-1.jpg","/images/produtos/cozinha/armario-cozinha-2.jpg"]', 'Torre de armários projetada para aproveitamento verticalizado do ambiente da cozinha. Estante generosa em litragem e nichos dedicados a micro-ondas ou forno.', 0, 5),
(7, 'Cozinha Planejada Compacta', 'Cozinhas', 'cozinha', '/images/produtos/cozinha/armario-cozinha.jpg', '["/images/produtos/cozinha/armario-cozinha.jpg"]', 'Solução otimizada em marcenaria para cozinhas compactas que necessitam de organização de mantimentos sem perda de circulação no ambiente.', 0, 4),
(8, 'Escritório Corporativo e Home Office', 'Escritórios', 'escritorio', '/images/produtos/escritorio/escritorio.jpg', '["/images/produtos/escritorio/escritorio.jpg"]', 'Estação de trabalho milimetricamente desenhada visando conforto ergonômico, espaçamento de monitores e armazenamento essencial de documentos em gaveteiros fluidos.', 1, 4),
(9, 'Fechamento de Hall de Apartamento', 'Halls', 'hall', '/images/produtos/hall/fechamento-hall-apt-1.jpg', '["/images/produtos/hall/fechamento-hall-apt-1.jpg","/images/produtos/hall/fechamento-hall-apt-2.jpg","/images/produtos/hall/fechamento-hall-apt-3.jpg","/images/produtos/hall/fechamento-hall-apt-4.jpg"]', 'Estrutura imponente de fechamento e privacidade total de Halls e Entradas de apartamento. Garante estética blindada em edifícios de alto padrão, mantendo discrição absoluta.', 0, 5),
(10, 'Painel de Apoio Executivo', 'Painéis', 'painel-sala', '/images/produtos/painel-sala/painel-escritorio.jpg', '["/images/produtos/painel-sala/painel-escritorio.jpg"]', 'Lindo painel amadeirado de design limpo, servindo perfeitamente de suporte ou textura para escritórios, salas de espera ou divisões parciais.', 0, 4),
(11, 'Painel Decorativo para Sala', 'Painéis', 'painel-sala', '/images/produtos/painel-sala/painel-sala-1.jpeg', '["/images/produtos/painel-sala/painel-sala-1.jpeg","/images/produtos/painel-sala/painel-sala-2.jpeg"]', 'Painel contínuo com acabamento formidável. Harmoniza de forma fluída com quadros, arandelas de iluminação ou simplesmente trazendo aquecimento em madeira ao ambiente frio.', 0, 5),
(12, 'Painel para Televisão (Home Theater)', 'Painéis', 'painel-sala', '/images/produtos/painel-sala/painel-tv.JPG', '["/images/produtos/painel-sala/painel-tv.JPG"]', 'Home planejado pensado cuidadosamente na passagem invisível de fiações, recuo dos fixadores de TV suspensa e resistência contra tombamento.', 0, 4),
(13, 'Mobiliário Comercial para Salão', 'Projetos Comerciais', 'planejados-comercio', '/images/produtos/planejados comercio/salao-1.jpg', '["/images/produtos/planejados comercio/salao-1.jpg","/images/produtos/planejados comercio/salao-2.jpg","/images/produtos/planejados comercio/salao-3.jpg"]', 'Conjunto corporativo robusto focado em Salões e Estéticas. Projetado para aguentar uso contínuo de clientes, fluxo intenso e fácil isolamento de áreas úmidas das cubas.', 1, 5);
