PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE categorias (
    slug TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    icone TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('armario','Armários','armario','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('banheiro','Banheiro','banho','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('cozinha','Cozinha','cozinha','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('escritorio','Escritório','escritorio','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('guarda-roupa','Guarda Roupa','guarda-roupa','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('hall','Hall','hall','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('painel-sala','Painel','painel','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('planejados-comercio','Comercial','comercio','2026-05-01 02:58:33');
INSERT INTO "categorias" ("slug","nome","icone","created_at") VALUES('mesa','Mesas','mesa','2026-05-02 03:07:41');
CREATE TABLE produtos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    categoria TEXT NOT NULL,
    categoriaSlug TEXT NOT NULL,
    imagemPrincipal TEXT NOT NULL,
    imagens TEXT, -- Armazenado como String JSON (Ex: '["url1", "url2"]')
    descricao TEXT,
    destaque INTEGER DEFAULT 0, -- 0 para False, 1 para True
    relevancia INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (categoriaSlug) REFERENCES categorias(slug)
);
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(1,'Armário para Sala','Armários','armario','/images/produtos/armario/armario-sala.jpeg','["/images/produtos/armario/armario-sala.jpeg"]','Armário planejado sob medida, ideal para a organização de itens e otimização de espaço na sala de estar, garantindo um visual minimalista e elegante.',0,4,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(2,'Armário Banheiro Planejado','Banheiros','banheiro','/images/produtos/banheiro/banheiro-1.jpg','["/images/produtos/banheiro/banheiro-1.jpg","/images/produtos/banheiro/banheiro-2.jpg","/images/produtos/banheiro/banheiro-3.jpg"]','Conjunto completo de marcenaria para banheiro planejado, composto por armários de excelente divisória e resistente à umidade típica do ambiente.',0,3,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(3,'Área Gourmet Planejada','Cozinhas','cozinha','/images/produtos/cozinha/area-gourmet.jpg','["/images/produtos/cozinha/area-gourmet.jpg"]','Projeto focado em áreas gourmet, perfeitamente alinhado com churrasqueiras e áreas de lazer, proporcionando funcionalidade e beleza nas suas recepções.',0,4,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(4,'Cozinha Planejada Completa','Cozinhas','cozinha','/images/produtos/cozinha/armario&movel-cozinha-.jpg','["/images/produtos/cozinha/armario&movel-cozinha-.jpg"]','Conjunto de móveis para bancada e pia da cozinha. Acabamento moderno que facilita a limpeza no dia-a-dia.',1,3,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(5,'Guarda Roupa Planejado Completo','Guarda Roupas','guarda-roupa','/images/produtos/guarda-roupa/guarda-roupa-1.jpg','["/images/produtos/guarda-roupa/guarda-roupa-1.jpg","/images/produtos/guarda-roupa/guarda-roupa-2.jpg","/images/produtos/guarda-roupa/guarda-roupa-3.jpg","/images/produtos/guarda-roupa/guarda-roupa-4.jpg"]','Guarda-roupa planejado completo com divisão inteligente, cabideiros reforçados, gavetas espaçosas e acabamento em MDF de altíssima qualidade.',0,5,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(6,'Cozinha Planejada Moderna','Cozinhas','cozinha','/images/produtos/cozinha/armario-cozinha-1.jpg','["/images/produtos/cozinha/armario-cozinha-1.jpg","/images/produtos/cozinha/armario-cozinha-2.jpg"]','Torre de armários projetada para aproveitamento verticalizado do ambiente da cozinha. Estante generosa em litragem e nichos dedicados a micro-ondas ou forno.',0,5,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(7,'Cozinha Planejada Compacta','Cozinhas','cozinha','/images/produtos/cozinha/armario-cozinha.jpg','["/images/produtos/cozinha/armario-cozinha.jpg"]','Solução otimizada em marcenaria para cozinhas compactas que necessitam de organização de mantimentos sem perda de circulação no ambiente.',0,4,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(8,'Escritório Corporativo e Home Office','Escritórios','escritorio','/images/produtos/escritorio/escritorio.jpg','["/images/produtos/escritorio/escritorio.jpg"]','Estação de trabalho milimetricamente desenhada visando conforto ergonômico, espaçamento de monitores e armazenamento essencial de documentos em gaveteiros fluidos.',1,4,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(9,'Fechamento de Hall de Apartamento','Halls','hall','/images/produtos/hall/fechamento-hall-apt-1.jpg','["/images/produtos/hall/fechamento-hall-apt-1.jpg","/images/produtos/hall/fechamento-hall-apt-2.jpg","/images/produtos/hall/fechamento-hall-apt-3.jpg","/images/produtos/hall/fechamento-hall-apt-4.jpg"]','Estrutura imponente de fechamento e privacidade total de Halls e Entradas de apartamento. Garante estética blindada em edifícios de alto padrão, mantendo discrição absoluta.',0,5,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(10,'Painel de Apoio Executivo','Painéis','painel-sala','/images/produtos/painel-sala/painel-escritorio.jpg','["/images/produtos/painel-sala/painel-escritorio.jpg"]','Lindo painel amadeirado de design limpo, servindo perfeitamente de suporte ou textura para escritórios, salas de espera ou divisões parciais.',0,4,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(11,'Painel Decorativo para Sala','Painéis','painel-sala','/images/produtos/painel-sala/painel-sala-1.jpeg','["/images/produtos/painel-sala/painel-sala-1.jpeg","/images/produtos/painel-sala/painel-sala-2.jpeg"]','Painel contínuo com acabamento formidável. Harmoniza de forma fluída com quadros, arandelas de iluminação ou simplesmente trazendo aquecimento em madeira ao ambiente frio.',0,5,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(12,'Painel para Televisão (Home Theater)','Painéis','painel-sala','/images/produtos/painel-sala/painel-tv.JPG','["/images/produtos/painel-sala/painel-tv.JPG"]','Home planejado pensado cuidadosamente na passagem invisível de fiações, recuo dos fixadores de TV suspensa e resistência contra tombamento.',0,4,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(13,'Mobiliário Comercial para Salão','Projetos Comerciais','planejados-comercio','/images/produtos/planejados comercio/salao-1.jpg','["/images/produtos/planejados comercio/salao-1.jpg","/images/produtos/planejados comercio/salao-2.jpg","/images/produtos/planejados comercio/salao-3.jpg"]','Conjunto corporativo robusto focado em Salões e Estéticas. Projetado para aguentar uso contínuo de clientes, fluxo intenso e fácil isolamento de áreas úmidas das cubas.',1,5,'2026-05-01 02:58:33');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(14,'Nova Mesa de Jantar Planejada','Cozinha','cozinha','/images/produtos/mesa/mesa-1.jpg','["/images/produtos/mesa/mesa-1.jpg","/images/produtos/mesa/mesa-2.jpg"]','Mesa em laca premium projetada sob medida com design contemporâneo e durabilidade absurda.',1,5,'2026-05-02 02:49:39');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(15,'Teste','Banheiro','banheiro','/images/produtos/teste/teste.jpg','["/images/produtos/teste/teste-1.jpg","/images/produtos/teste/teste-2.jpg"]','Lorem ipsum',0,1,'2026-05-02 02:53:52');
INSERT INTO "produtos" ("id","nome","categoria","categoriaSlug","imagemPrincipal","imagens","descricao","destaque","relevancia","created_at") VALUES(16,'Teste','Banheiro','banheiro','/images/produtos/teste/teste.jpg','["/images/produtos/teste/teste-1.jpg","/images/produtos/teste/teste-2.jpg"]','Lorem ipsum',0,1,'2026-05-02 03:05:51');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('produtos',16);
